import { CommonModule } from '@angular/common';
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/api.service';

@Component({
  standalone:true,
  imports:[CommonModule,FormsModule],
  template:`
    <section class="page-head"><div><p class="eyebrow">Super Admin</p><h1>Department Admin Accounts</h1><p>Create and edit Admin, CS, CA, and Vehicle Department users.</p></div><button type="button" (click)="startCreate()">Add account</button></section>
    <div class="toolbar panel"><input [(ngModel)]="search" placeholder="Search name, email, phone or role"><select [(ngModel)]="roleFilter"><option value="">All roles</option><option *ngFor="let role of roles" [value]="role.value">{{role.label}}</option></select></div>
    <article class="panel table-panel"><div class="responsive-table"><table><thead><tr><th>Name</th><th>Role</th><th>Contact</th><th>Status</th><th>Last login</th><th></th></tr></thead><tbody><tr *ngFor="let user of filteredUsers"><td><strong>{{user.fullName}}</strong><small>{{user.email}}</small></td><td><span class="badge">{{roleLabel(user.role)}}</span></td><td>{{user.phone}}</td><td><span [class.inactive]="!user.isActive">{{user.isActive?'Active':'Inactive'}}</span></td><td>{{user.lastLoginAt?(user.lastLoginAt|date:'medium'):'Never'}}</td><td><button type="button" class="ghost-button" (click)="startEdit(user)">Edit</button></td></tr><tr *ngIf="!filteredUsers.length"><td colspan="6" class="empty">No matching department admin users.</td></tr></tbody></table></div></article>

    <div class="modal-backdrop" *ngIf="editing"><form class="panel modal" (ngSubmit)="save()"><div class="modal-head"><h2>{{form.id?'Edit':'Create'}} account</h2><button type="button" class="close" (click)="editing=false">×</button></div><div class="fields"><label>Full name<input name="name" [(ngModel)]="form.fullName" required></label><label>Email<input name="email" type="email" [(ngModel)]="form.email" required></label><label>Phone<input name="phone" [(ngModel)]="form.phone" required></label><label>Role<select name="role" [(ngModel)]="form.role" required><option *ngFor="let role of roles" [value]="role.value">{{role.label}}</option></select></label><label class="wide">{{form.id?'New password (leave blank to keep current)':'Temporary password'}}<input name="password" type="password" [(ngModel)]="form.password" [required]="!form.id" minlength="8"></label><label class="check" *ngIf="form.id"><input name="active" type="checkbox" [(ngModel)]="form.isActive"> Account active</label></div><div class="permissions"><h3>Extra individual permissions</h3><p>Role permissions apply automatically. Select only additional access for this user.</p><label *ngFor="let permission of permissions"><input type="checkbox" [checked]="form.permissionIds.includes(permission.id)" (change)="togglePermission(permission.id,$any($event.target).checked)">{{permission.code}}</label></div><p class="error">{{error}}</p><div class="actions"><button type="button" class="ghost-button" (click)="editing=false">Cancel</button><button [disabled]="saving">{{saving?'Saving…':'Save account'}}</button></div></form></div>
    <div class="notice" *ngIf="message">{{message}}</div>
  `,
  styles:[`
    .toolbar{display:flex;gap:12px;margin-bottom:18px}.toolbar input{flex:1}.toolbar select{max-width:240px}.table-panel{padding:0;overflow:hidden}td small{display:block;color:var(--muted);margin-top:3px}.badge{background:var(--brand-light);color:var(--brand-dark);padding:5px 9px;border-radius:999px;font-size:12px;font-weight:700}.inactive{color:#b91c1c}.empty{text-align:center;color:var(--muted);padding:30px}.modal-backdrop{position:fixed;inset:0;background:#0f172a99;z-index:50;display:grid;place-items:center;padding:20px}.modal{width:min(760px,100%);max-height:92vh;overflow:auto}.modal-head{display:flex;justify-content:space-between;align-items:center}.close{background:transparent;color:var(--muted);box-shadow:none;font-size:28px;padding:0}.fields{display:grid;grid-template-columns:1fr 1fr;gap:14px}.wide{grid-column:1/-1}.check{display:flex;align-items:center;gap:8px}.check input,.permissions input{width:auto}.permissions{margin-top:20px;border-top:1px solid var(--line);padding-top:14px;display:flex;flex-wrap:wrap;gap:10px 18px}.permissions h3,.permissions p{width:100%;margin:0}.permissions p{color:var(--muted);font-size:13px}.permissions label{display:flex;align-items:center;gap:6px;font-size:13px}.actions{display:flex;justify-content:flex-end;gap:10px;margin-top:20px}.notice{position:fixed;right:24px;bottom:24px;background:#ecfdf5;color:#047857;padding:12px 18px;border-radius:10px}@media(max-width:650px){.toolbar,.fields{display:grid;grid-template-columns:1fr}.toolbar select,.wide{max-width:none;grid-column:auto}}
  `]
})
export class AdminUsersComponent{
  private api=inject(ApiService);users:any[]=[];permissions:any[]=[];search='';roleFilter='';editing=false;saving=false;error='';message='';
  roles=[{value:'Admin',label:'Admin'},{value:'SubAdmin',label:'Sub Admin'},{value:'CS',label:'CS Department'},{value:'CA',label:'CA Department'},{value:'VehicleDepartment',label:'Vehicle Department'}];
  form:any={};constructor(){this.load()}
  get filteredUsers(){const q=this.search.trim().toLowerCase();return this.users.filter(x=>(!this.roleFilter||x.role===this.roleFilter)&&(!q||`${x.fullName} ${x.email} ${x.phone} ${x.role}`.toLowerCase().includes(q)))}
  roleLabel(value:string){return this.roles.find(x=>x.value===value)?.label??value}
  load(){this.api.adminAccounts().subscribe({next:x=>this.users=x,error:e=>this.error=e.error?.message??'Could not load accounts.'});this.api.accessControl().subscribe({next:x=>this.permissions=(x.groups??[]).flatMap((g:any)=>g.permissions),error:e=>this.error=e.error?.message??'Could not load permissions.'})}
  startCreate(){this.form={id:null,fullName:'',email:'',phone:'',role:'Admin',password:'',isActive:true,permissionIds:[]};this.error='';this.editing=true}
  startEdit(user:any){this.form={...user,password:'',permissionIds:[...(user.permissionIds??[])]};this.error='';this.editing=true}
  togglePermission(id:number,on:boolean){this.form.permissionIds=on?[...new Set([...this.form.permissionIds,id])]:this.form.permissionIds.filter((x:number)=>x!==id)}
  save(){this.saving=true;this.error='';const request={fullName:this.form.fullName,email:this.form.email,phone:this.form.phone,role:this.form.role,password:this.form.password||null,isActive:this.form.isActive};const operation=this.form.id?this.api.updateAdminUser(this.form.id,request):this.api.createAdminUser(request);operation.subscribe({next:(response:any)=>{const userId=this.form.id??response?.id;const permissionSave=userId?this.api.setUserPermissions(userId,this.form.permissionIds):null;if(permissionSave)permissionSave.subscribe({next:()=>this.done(),error:e=>this.failed(e)});else this.done()},error:e=>this.failed(e)})}
  private done(){this.saving=false;this.editing=false;this.message='Account saved successfully.';this.load()}
  private failed(e:any){this.saving=false;this.error=e.error?.message??'Could not save account.'}
}
