import { CommonModule } from '@angular/common';
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/api.service';

@Component({standalone:true,imports:[CommonModule,FormsModule],template:`
<section class="page-head"><div><p class="eyebrow">Super Admin</p><h1>Fixed Department Accounts</h1><p>Create Sub Admin, CA, Transportation, and Brand &amp; IT users.</p></div><button type="button" (click)="startCreate()">Add account</button></section>
<div class="toolbar panel"><input [(ngModel)]="search" placeholder="Search accounts"><select [(ngModel)]="roleFilter"><option value="">All roles</option><option *ngFor="let role of roles" [value]="role.value">{{role.label}}</option></select></div>
<article class="panel"><div class="responsive-table"><table><thead><tr><th>Name</th><th>Role</th><th>Contact</th><th>Status</th><th></th></tr></thead><tbody><tr *ngFor="let user of filteredUsers"><td><strong>{{user.fullName}}</strong><small>{{user.email}}</small></td><td>{{roleLabel(user.role)}}</td><td>{{user.phone}}</td><td>{{user.isActive?'Active':'Inactive'}}</td><td><button type="button" class="ghost-button" (click)="startEdit(user)">Edit</button></td></tr></tbody></table></div></article>
<div class="modal-backdrop" *ngIf="editing"><form class="panel modal" (ngSubmit)="save()"><div class="modal-head"><h2>{{form.id?'Edit':'Create'}} account</h2><button type="button" class="ghost-button" (click)="editing=false">Close</button></div><div class="fields"><label>Full name<input name="name" [(ngModel)]="form.fullName" required></label><label>Email<input name="email" type="email" [(ngModel)]="form.email" required></label><label>Phone<input name="phone" [(ngModel)]="form.phone" required></label><label>Fixed role<select name="role" [(ngModel)]="form.role" required><option *ngFor="let role of roles" [value]="role.value">{{role.label}}</option></select></label><label>{{form.id?'New password (optional)':'Temporary password'}}<input name="password" type="password" [(ngModel)]="form.password" [required]="!form.id" minlength="8"></label><label *ngIf="form.id"><input name="active" type="checkbox" [(ngModel)]="form.isActive"> Account active</label></div><p class="error">{{error}}</p><div class="actions"><button type="button" class="ghost-button" (click)="editing=false">Cancel</button><button [disabled]="saving">{{saving?'Saving…':'Save account'}}</button></div></form></div><div class="notice" *ngIf="message">{{message}}</div>
`,styles:[`.toolbar{display:flex;gap:12px;margin-bottom:18px}.toolbar input{flex:1}td small{display:block;color:var(--muted)}.modal-backdrop{position:fixed;inset:0;background:#0f172a99;z-index:50;display:grid;place-items:center;padding:20px}.modal{width:min(680px,100%)}.modal-head,.actions{display:flex;justify-content:space-between;align-items:center}.fields{display:grid;grid-template-columns:1fr 1fr;gap:14px}.actions{justify-content:flex-end;gap:10px;margin-top:20px}.notice{position:fixed;right:24px;bottom:24px;background:#ecfdf5;color:#047857;padding:12px 18px;border-radius:10px}`]})
export class AdminUsersComponent{
 private api=inject(ApiService);users:any[]=[];search='';roleFilter='';editing=false;saving=false;error='';message='';form:any={};
 roles=[{value:'SubAdmin',label:'Sub Admin'},{value:'CA',label:'CA Department'},{value:'Transportation',label:'Transportation'},{value:'BrandAndIT',label:'Brand & IT'}];
 constructor(){this.load()} get filteredUsers(){const q=this.search.trim().toLowerCase();return this.users.filter(x=>(!this.roleFilter||x.role===this.roleFilter)&&(!q||`${x.fullName} ${x.email} ${x.phone} ${x.role}`.toLowerCase().includes(q)))} roleLabel(v:string){return this.roles.find(x=>x.value===v)?.label??v}
 load(){this.api.adminAccounts().subscribe({next:x=>this.users=x,error:e=>this.error=e.error?.message??'Could not load accounts.'})}
 startCreate(){this.form={id:null,fullName:'',email:'',phone:'',role:'SubAdmin',password:'',isActive:true};this.error='';this.editing=true} startEdit(user:any){this.form={...user,password:''};this.error='';this.editing=true}
 save(){this.saving=true;this.error='';const request={fullName:this.form.fullName,email:this.form.email,phone:this.form.phone,role:this.form.role,password:this.form.password||null,isActive:this.form.isActive};const op=this.form.id?this.api.updateAdminUser(this.form.id,request):this.api.createAdminUser(request);op.subscribe({next:()=>{this.saving=false;this.editing=false;this.message='Account saved successfully.';this.load()},error:e=>{this.saving=false;this.error=e.error?.message??'Could not save account.'}})}
}
