import { CommonModule } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { forkJoin } from 'rxjs';
import { ApiService } from '../../core/api.service';
import { AvailableLeadCustomer, CreateLeadRequest, Project, SalesExecutive } from '../../models/crm.models';

@Component({standalone:true,imports:[CommonModule,FormsModule,RouterLink],template:`
<section class="page-head"><div><p class="eyebrow">Pipeline entry</p><h1>Add New Lead</h1><p class="page-copy">Record prospect details and assign the lead to the right sales employee.</p></div><a routerLink="/leads" class="back">← Lead directory</a></section>
<form class="lead-form" (ngSubmit)="create()" #leadForm="ngForm"><header><span>01</span><div><h2>Lead information</h2><p>Required fields are marked with an asterisk.</p></div></header><div class="grid">
<label class="wide">Existing customer (optional)<select name="customer" [(ngModel)]="selectedCustomerId" (ngModelChange)="selectCustomer($event)"><option [ngValue]="null">Create as a new prospect</option><option *ngFor="let customer of customers" [ngValue]="customer.id">{{customer.name}} · {{customer.phone}}</option></select></label>
<label>Lead name *<input name="name" [(ngModel)]="form.customerName" required></label><label>Primary phone *<input name="phone" [(ngModel)]="form.phone" required></label><label>Alternative phone<input name="alternativePhone" [(ngModel)]="form.alternativePhone"></label><label>Email<input name="email" type="email" [(ngModel)]="form.email"></label><label>Address<input name="address" [(ngModel)]="form.address"></label><label>Preferred location<input name="preferredLocation" [(ngModel)]="form.preferredLocation"></label><label>Budget range<input name="budgetRange" [(ngModel)]="form.budgetRange"></label><label>Project<select name="project" [(ngModel)]="form.projectId"><option [ngValue]="null">No project selected</option><option *ngFor="let project of projects" [ngValue]="project.id">{{project.name}}</option></select></label><label>Assign employee *<select name="assigned" [(ngModel)]="form.assignedToId" required><option [ngValue]="null">Select sales employee</option><option *ngFor="let employee of employees" [ngValue]="employee.id">{{employee.fullName}}</option></select></label><label>Lead source<select name="source" [(ngModel)]="form.source"><option [ngValue]="11">Company</option><option [ngValue]="12">Self</option><option [ngValue]="5">Referral</option></select></label>
<ng-container *ngIf="form.source===5"><label>Referrer name<input name="referrerName" [(ngModel)]="form.referrerName"></label><label>Referrer phone<input name="referrerPhone" [(ngModel)]="form.referrerPhone"></label></ng-container><label class="wide">Remarks<textarea name="remarks" rows="3" [(ngModel)]="form.remarks"></textarea></label></div><p class="error" *ngIf="error">{{error}}</p><footer><a routerLink="/leads" class="cancel">Cancel</a><button [disabled]="saving||leadForm.invalid">{{saving?'Creating…':'Create Lead'}}</button></footer></form>
`,styles:[`:host{display:block}.back,.cancel{padding:10px 14px;border:1px solid var(--line);border-radius:10px;background:#fff;color:#334155;font-weight:700}.lead-form{max-width:980px;margin:auto;padding:24px;border:1px solid var(--line);border-radius:18px;background:#fff;box-shadow:var(--shadow)}.lead-form header{display:flex;align-items:center;gap:11px;padding-bottom:17px;margin-bottom:18px;border-bottom:1px solid var(--line)}.lead-form header>span{display:grid;place-items:center;width:38px;height:38px;border-radius:11px;background:#e6f4f2;color:#0f766e;font-weight:900}.lead-form h2,.lead-form p{margin:0}.lead-form header p{margin-top:3px;color:#64748b;font-size:11px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.grid label{display:grid;gap:6px;color:#475569;font-size:11px;font-weight:800}.grid input,.grid select{height:42px}.wide{grid-column:1/-1}.lead-form footer{display:flex;justify-content:flex-end;gap:9px;padding-top:18px;margin-top:18px;border-top:1px solid var(--line)}@media(max-width:650px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}.lead-form{padding:18px}}`]} )
export class CreateLeadComponent implements OnInit{private api=inject(ApiService);private router=inject(Router);employees:SalesExecutive[]=[];projects:Project[]=[];customers:AvailableLeadCustomer[]=[];selectedCustomerId:number|null=null;saving=false;error='';form:CreateLeadRequest={customerId:null,customerName:'',phone:'',alternativePhone:null,email:null,address:null,budgetRange:null,preferredLocation:null,projectId:null,source:11,assignedToId:null,remarks:null};ngOnInit(){forkJoin({employees:this.api.salesExecutives(),projects:this.api.projects(),customers:this.api.customersAvailableForLead()}).subscribe(data=>{this.employees=data.employees;this.projects=data.projects;this.customers=data.customers;});}selectCustomer(id:number|null){const customer=this.customers.find(item=>item.id===id);this.form={...this.form,customerId:id,customerName:customer?.name??'',phone:customer?.phone??'',alternativePhone:customer?.alternativePhone??null,email:customer?.email??null,address:customer?.address??null,assignedToId:customer?.assignedToId??null};}create(){this.saving=true;this.error='';this.api.createLead(this.form).subscribe({next:()=>void this.router.navigate(['/leads']),error:error=>{this.saving=false;this.error=error.error?.message||'Could not create lead.';}});}}
