import { CommonModule } from '@angular/common';
import { Component, inject, OnInit } from '@angular/core';
import { RouterLink } from '@angular/router';
import { forkJoin } from 'rxjs';
import { ApiService } from '../../core/api.service';

@Component({standalone:true,imports:[CommonModule,RouterLink],template:`
<section class="page-head"><div><p class="eyebrow">CA Department</p><h1>Collections and dues</h1><p class="subtitle">Employee-month collections and customer due notifications are independent records.</p></div><a routerLink="/payments/record">Add collection or due</a></section>
<div class="metrics"><article class="panel"><span>Total monthly collection</span><strong>{{collectionTotal|number:'1.2-2'}}</strong></article><article class="panel due"><span>Unpaid customer due</span><strong>{{dueTotal|number:'1.2-2'}}</strong></article></div>
<article class="panel"><h2>Monthly collections by sales employee</h2><div class="responsive"><table><thead><tr><th>Month</th><th>Sales employee</th><th>Team / group</th><th>Entered by</th><th>Remarks</th><th class="right">Amount</th></tr></thead><tbody><tr *ngFor="let row of collections"><td>{{row.month|date:'MMMM yyyy'}}</td><td><strong>{{row.salesExecutive}}</strong></td><td>{{row.team||'—'}} / {{row.group||'—'}}</td><td>{{row.recordedBy||'—'}}</td><td>{{row.remarks||'—'}}</td><td class="right"><strong>{{row.amount|number:'1.2-2'}}</strong></td></tr><tr *ngIf="!collections.length"><td colspan="6">No monthly collections recorded.</td></tr></tbody></table></div></article>
<article class="panel"><h2>Customer dues</h2><div class="responsive"><table><thead><tr><th>Due date</th><th>Customer file</th><th>Assigned employee</th><th>Status</th><th>Remarks</th><th class="right">Due</th><th>CA action</th></tr></thead><tbody><tr *ngFor="let row of dues"><td>{{row.dueDate|date}}</td><td><strong>{{row.fileId}}</strong><small><br>{{row.customer}}</small></td><td>{{row.salesExecutive||'Unassigned'}}</td><td><span class="status" [class.paid]="row.status===1">{{dueStatuses[row.status]}}</span><small *ngIf="row.paidAt"><br>{{row.paidAt|date:'medium'}}</small></td><td>{{row.remarks||'—'}}</td><td class="right"><strong>{{row.amount|number:'1.2-2'}}</strong></td><td><button *ngIf="row.status===0" (click)="markPaid(row)">Mark paid</button><button class="ghost-button" *ngIf="row.status!==0" (click)="reopen(row)">Reopen</button></td></tr><tr *ngIf="!dues.length"><td colspan="7">No customer dues recorded.</td></tr></tbody></table></div></article><p class="error" *ngIf="error">{{error}}</p>
`,styles:[`.subtitle{color:var(--muted)}.metrics{display:grid;grid-template-columns:repeat(2,minmax(220px,1fr));gap:16px;margin-bottom:18px}.metrics article{display:grid;gap:7px}.metrics span{color:var(--muted)}.metrics strong{font-size:24px}.due strong{color:#b91c1c}.panel+.panel{margin-top:18px}.responsive{overflow:auto}.right{text-align:right}.status{padding:4px 8px;border-radius:20px;background:#fee2e2;color:#b91c1c;font-weight:800}.status.paid{background:#d1fae5;color:#047857}td button{white-space:nowrap}table{width:100%}@media(max-width:700px){.metrics{grid-template-columns:1fr}}`]})
export class PaymentsComponent implements OnInit{
 private api=inject(ApiService);collections:any[]=[];dues:any[]=[];error='';dueStatuses=['Unpaid','Paid','Cancelled'];
 get collectionTotal(){return this.collections.reduce((sum,row)=>sum+Number(row.amount),0)}get dueTotal(){return this.dues.filter(x=>x.status===0).reduce((sum,row)=>sum+Number(row.amount),0)}
 ngOnInit(){this.load()}load(){forkJoin({collections:this.api.monthlyCollections(),dues:this.api.customerDues()}).subscribe({next:x=>{this.collections=x.collections;this.dues=x.dues},error:e=>this.error=e.error?.message||'Could not load collections and dues.'})}
 markPaid(row:any){const remarks=prompt(`Mark file ${row.fileId} due as paid. Optional CA remarks:`)||'';this.api.markCustomerDuePaid(row.id,remarks).subscribe({next:()=>this.load(),error:e=>this.error=e.error?.message||'Could not mark the due paid.'})}
 reopen(row:any){const remarks=prompt(`Reason for reopening file ${row.fileId} due:`);if(!remarks?.trim())return;this.api.reopenCustomerDue(row.id,remarks.trim()).subscribe({next:()=>this.load(),error:e=>this.error=e.error?.message||'Could not reopen the due.'})}
}
