import {CommonModule} from '@angular/common';
import {Component,OnInit,inject} from '@angular/core';
import {ActivatedRoute,RouterLink} from '@angular/router';
import {ApiService} from '../../core/api.service';
import {ReportPdfService} from '../../core/report-pdf.service';

@Component({standalone:true,imports:[CommonModule,RouterLink],template:`
<div class="toolbar no-print"><a routerLink="/reports">← Reports</a><div><button class="ghost-button" (click)="csv()">Download CSV</button><button (click)="pdf()">Download PDF</button></div></div>
<section class="profile" *ngIf="kpi"><div><p class="eyebrow">Individual performance report</p><h1>{{kpi.employee}}</h1><p>{{kpi.team}} · {{from|date:'mediumDate'}} — {{to|date:'mediumDate'}}</p></div><article><span>Overall KPI</span><strong>{{kpi.score|number:'1.0-2'}}</strong><b>{{kpi.rating}}</b></article></section>
<section class="summary" *ngIf="kpi"><article><span>Won</span><b>{{kpi.won}}</b></article><article><span>Lost</span><b>{{kpi.lost}}</b></article><article class="risk"><span>Returned</span><b>{{kpi.returned}}</b></article><article><span>Sales units</span><b>{{kpi.salesUnits}}</b></article><article><span>Collections</span><b>{{kpi.collections|currency:'BDT':'symbol':'1.0-0':'en-BD'}}</b></article></section>
<section class="formula" *ngIf="formula"><b>KPI formula</b><p>{{formula.score}}</p><small>{{formula.note}}</small></section>
<section class="panel table"><header><div><p class="eyebrow">Monthly breakdown</p><h2>KPI performance by month</h2></div></header><div class="scroll"><table><thead><tr><th>Month</th><th>KPI</th><th>Rating</th><th>Won</th><th>Lost</th><th>Returned</th><th>Response</th><th>Sales Units</th><th>Sales Target</th><th>Collections</th><th>Collection Target</th><th>Win Rate</th><th>Follow-up</th></tr></thead><tbody><tr *ngFor="let r of months"><td>{{r.month|date:'MMM yyyy'}}</td><td><strong>{{r.score|number:'1.0-2'}}</strong></td><td>{{r.rating}}</td><td>{{r.won}}</td><td>{{r.lost}}</td><td class="risk">{{r.returned}}</td><td>{{r.responseDiscipline|number:'1.0-1'}}%</td><td>{{r.salesUnits}}</td><td>{{r.salesTarget}}</td><td>{{r.collections|currency:'BDT':'symbol':'1.0-0':'en-BD'}}</td><td>{{r.collectionTarget|currency:'BDT':'symbol':'1.0-0':'en-BD'}}</td><td>{{r.winRate|number:'1.0-1'}}%</td><td>{{r.followupCoverage|number:'1.0-1'}}%</td></tr></tbody></table></div></section><p class="error">{{error}}</p>
`,styles:[`.toolbar,.toolbar>div,.profile{display:flex;justify-content:space-between;gap:10px}.toolbar a{color:var(--brand);font-weight:800}.profile{align-items:center;margin:20px 0}.profile h1{margin:3px 0}.profile p{color:var(--muted)}.profile article{min-width:180px;padding:16px;border-radius:14px;background:var(--brand);color:#fff;display:grid;text-align:center}.profile article strong{font-size:32px}.summary{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:16px 0}.summary article{padding:15px;background:#fff;border:1px solid var(--line);border-radius:11px;display:grid}.summary span{font-size:10px;color:var(--muted);text-transform:uppercase}.summary b{font-size:19px}.risk{background:#fff7ed!important;color:#9a3412}.formula{padding:14px;background:#eef2ff;border:1px solid #c7d2fe;border-radius:10px;margin-bottom:15px}.formula p{margin:4px 0}.formula small{color:var(--muted)}.table{padding:0;overflow:hidden}.table header{padding:15px}.table h2{margin:2px 0}.scroll{overflow:auto}table{width:100%;border-collapse:collapse;min-width:1300px}th,td{padding:11px;border-bottom:1px solid var(--line);text-align:right;white-space:nowrap;font-size:11px}th:first-child,td:first-child{text-align:left}th{background:#f8fafc;text-transform:uppercase;font-size:9px;color:var(--muted)}.error{color:#b91c1c}@media(max-width:700px){.summary{grid-template-columns:1fr 1fr}.profile{display:block}.profile article{margin-top:12px}}@media print{.no-print{display:none!important}.summary{grid-template-columns:repeat(5,1fr)}table{min-width:0}th,td{font-size:7px;padding:5px}@page{size:A4 landscape;margin:8mm}}`]})
export class EmployeeReportComponent implements OnInit{private api=inject(ApiService);private route=inject(ActivatedRoute);private reportPdf=inject(ReportPdfService);id=Number(this.route.snapshot.paramMap.get('id'));from=this.route.snapshot.queryParamMap.get('from')||`${new Date().getFullYear()}-01-01`;to=this.route.snapshot.queryParamMap.get('to')||new Date().toISOString().slice(0,10);kpi:any;months:any[]=[];formula:any;error='';
 ngOnInit(){this.api.reportWorkspace(this.from,this.to,this.id,null).subscribe({next:r=>{this.kpi=r.kpis?.[0];this.months=r.employeeMonthly||[];this.formula=r.formula},error:e=>this.error=e.error?.message||'Could not load employee report.'})}
 async pdf(){if(!this.kpi)return;const columns=[{key:'month',label:'Month'},{key:'score',label:'KPI Score'},{key:'rating',label:'Rating'},{key:'won',label:'Won'},{key:'lost',label:'Lost'},{key:'returned',label:'Returned'},{key:'responseDiscipline',label:'Response %'},{key:'salesUnits',label:'Sales Units'},{key:'salesTarget',label:'Sales Target'},{key:'collections',label:'Collections'},{key:'collectionTarget',label:'Collection Target'},{key:'winRate',label:'Win Rate %'},{key:'followupCoverage',label:'Follow-up %'}];try{await this.reportPdf.download(`${this.kpi.employee} - Employee KPI Report`,`${this.kpi.team} | Overall KPI ${this.kpi.score} (${this.kpi.rating})`,`${this.from} to ${this.to}`,columns,this.months,(v,key)=>this.pdfValue(v,key),`${this.kpi.employee}-kpi-${this.from}-${this.to}`)}catch(e:any){this.error=e?.message||'Could not create the PDF report.'}}
 pdfValue(v:any,key:string){if(v===null||v===undefined)return '-';if(key==='month')return new Date(v).toLocaleDateString('en-BD',{month:'short',year:'numeric'});if(key==='collections'||key==='collectionTarget')return new Intl.NumberFormat('en-BD',{style:'currency',currency:'BDT',maximumFractionDigits:0}).format(v);if(key==='responseDiscipline'||key==='winRate'||key==='followupCoverage')return `${Number(v).toFixed(1)}%`;return String(v)}
 csv(){if(!this.months.length)return;const keys=Object.keys(this.months[0]);const q=(v:any)=>`"${String(v??'').replace(/"/g,'""')}"`;const csv='\ufeff'+keys.map(q).join(',')+'\r\n'+this.months.map(r=>keys.map(k=>q(r[k])).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`${this.kpi?.employee||'employee'}-kpi-${this.from}-${this.to}.csv`;a.click()}}
