import { CommonModule } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/api.service';

type TabKey='kpi'|'leads'|'sales'|'collections'|'returned'|'projects';
type Column={key:string;label:string;type?:'number'|'money'|'percent'|'date'|'datetime';accent?:boolean};

@Component({standalone:true,imports:[CommonModule,FormsModule],template:`
<section class="page-head"><div><p class="eyebrow">Performance intelligence</p><h1>CRM Reports</h1><p>Focused, traceable reports for employee performance and business decisions.</p></div><div class="actions"><button class="ghost-button" (click)="exportCsv()" [disabled]="!rows.length">Export CSV</button><button (click)="load()" [disabled]="loading">{{loading?'Loading…':'Refresh'}}</button></div></section>

<section class="panel filters"><label>From<input type="date" [(ngModel)]="from"></label><label>To<input type="date" [(ngModel)]="to"></label><label>Employee<select [(ngModel)]="employeeId"><option [ngValue]="null">All employees</option><option *ngFor="let x of employees" [ngValue]="x.id">{{x.fullName}}</option></select></label><label>Project<select [(ngModel)]="projectId"><option [ngValue]="null">All projects</option><option *ngFor="let x of projects" [ngValue]="x.id">{{x.name}}</option></select></label><button (click)="load()" [disabled]="loading">Apply filters</button></section>
<p class="error" *ngIf="error">{{error}}</p>

<nav class="report-tabs" aria-label="Report sections"><button *ngFor="let tab of tabs" [class.active]="active===tab.key" (click)="select(tab.key)"><span>{{tab.icon}}</span><strong>{{tab.label}}</strong><small>{{tab.description}}</small></button></nav>

<section class="report-heading"><div><p class="eyebrow">{{activeTab.label}}</p><h2>{{activeTab.title}}</h2><p>{{activeTab.help}}</p></div><div class="period"><span>Reporting period</span><strong>{{from|date:'mediumDate'}} — {{to|date:'mediumDate'}}</strong><small>Generated {{generatedAt|date:'medium'}}</small></div></section>

<section class="formula-card" *ngIf="active==='kpi'&&formula"><header><div><span class="formula-mark">ƒ</span><div><strong>Employee KPI formula</strong><p>{{formula.score}}</p></div></div><button class="text-button" (click)="showFormula=!showFormula">{{showFormula?'Hide':'View'}} calculation details</button></header><div class="formula-grid" *ngIf="showFormula"><article><b>30%</b><span>Response discipline</span><small>{{formula.responseDiscipline}}</small></article><article><b>25%</b><span>Sales achievement</span><small>{{formula.salesAchievement}}</small></article><article><b>20%</b><span>Collection achievement</span><small>{{formula.collectionAchievement}}</small></article><article><b>15%</b><span>Win rate</span><small>{{formula.winRate}}</small></article><article><b>10%</b><span>Follow-up coverage</span><small>{{formula.followupCoverage}}</small></article><p>{{formula.note}}</p></div></section>

<section class="panel report-table"><div class="table-scroll"><table><thead><tr><th *ngFor="let column of columns" [class.accent]="column.accent">{{column.label}}</th></tr></thead><tbody><tr *ngFor="let row of rows"><td *ngFor="let column of columns" [class.accent]="column.accent"><ng-container [ngSwitch]="column.key"><span *ngSwitchCase="'rating'" class="rating" [class]="'rating '+ratingClass(row[column.key])">{{row[column.key]}}</span><strong *ngSwitchCase="'score'" class="score">{{row[column.key]|number:'1.0-2'}}</strong><span *ngSwitchDefault>{{display(row[column.key],column.type)}}</span></ng-container></td></tr><tr *ngIf="!loading&&!rows.length"><td [attr.colspan]="columns.length" class="empty">No records match the selected filters.</td></tr></tbody><tfoot *ngIf="totals&&rows.length"><tr><th *ngFor="let column of columns" [class.accent]="column.accent">{{column.key===columns[0].key?'Total':totalValue(column)}}</th></tr></tfoot></table></div><footer><span>{{rows.length|number}} {{rows.length===1?'row':'rows'}}</span><span>Use the filters above to refine this report.</span></footer></section>
`,styles:[`
.actions{display:flex;gap:8px}.filters{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr)) auto;align-items:end;gap:12px;margin-bottom:20px}.filters label{display:grid;gap:6px;font-size:12px;font-weight:800;color:var(--muted)}
.report-tabs{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin:4px 0 26px}.report-tabs button{min-height:94px;padding:13px;text-align:left;display:grid;grid-template-columns:auto 1fr;grid-template-rows:auto auto;gap:3px 8px;background:#fff;color:var(--text);border:1px solid var(--line);box-shadow:none}.report-tabs button>span{grid-row:1/3;width:30px;height:30px;display:grid;place-items:center;border-radius:8px;background:var(--panel-soft);color:var(--brand);font-weight:900}.report-tabs strong{font-size:13px}.report-tabs small{font-size:10px;color:var(--muted);line-height:1.3}.report-tabs button.active{border-color:var(--brand);box-shadow:0 0 0 1px var(--brand);background:var(--brand-light)}
.report-heading{display:flex;justify-content:space-between;gap:24px;align-items:end;margin:0 0 16px}.report-heading h2{margin:2px 0 5px}.report-heading p{margin:0;color:var(--muted)}.period{min-width:245px;display:grid;text-align:right}.period span,.period small{font-size:11px;color:var(--muted)}
.formula-card{border:1px solid #c7d2fe;background:linear-gradient(135deg,#eef2ff,#fff);border-radius:14px;padding:17px;margin-bottom:16px}.formula-card header,.formula-card header>div{display:flex;align-items:center;justify-content:space-between;gap:12px}.formula-card header>div{justify-content:flex-start}.formula-card p{margin:3px 0;color:var(--muted);font-size:12px}.formula-mark{width:38px;height:38px;border-radius:10px;background:#3730a3;color:#fff;display:grid;place-items:center;font-size:22px}.text-button{background:transparent;color:#3730a3;border:0;box-shadow:none}.formula-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:15px}.formula-grid article{padding:11px;background:#fff;border:1px solid #e0e7ff;border-radius:9px;display:grid}.formula-grid b{font-size:19px;color:#3730a3}.formula-grid span{font-size:11px;font-weight:800}.formula-grid small{font-size:9px;color:var(--muted)}.formula-grid>p{grid-column:1/-1}
.report-table{padding:0;overflow:hidden}.table-scroll{overflow:auto}table{width:100%;border-collapse:separate;border-spacing:0;min-width:850px}th,td{padding:13px 14px;border-bottom:1px solid var(--line);text-align:right;white-space:nowrap}th:first-child,td:first-child{text-align:left;position:sticky;left:0;background:inherit}thead th{position:sticky;top:0;background:#f8fafc!important;color:#475569;text-transform:uppercase;letter-spacing:.04em;font-size:10px;z-index:1}tbody tr{background:#fff}tbody tr:nth-child(even){background:#fafcff}tbody tr:hover{background:#f1f5f9}tbody td{font-size:12px}.accent{background:#fff7ed!important;color:#9a3412!important}.score{font-size:16px;color:#0f172a}.rating{padding:5px 8px;border-radius:999px;font-weight:800;font-size:10px}.rating.excellent{background:#dcfce7;color:#166534}.rating.good{background:#dbeafe;color:#1d4ed8}.rating.improve{background:#fef3c7;color:#92400e}.rating.critical{background:#fee2e2;color:#b91c1c}tfoot th{background:#f1f5f9;font-size:12px;border-bottom:0}.empty{text-align:center!important;padding:35px!important;color:var(--muted);position:static!important}.report-table>footer{display:flex;justify-content:space-between;padding:11px 14px;color:var(--muted);font-size:10px;border-top:1px solid var(--line)}.error{color:#b91c1c}
@media(max-width:1050px){.report-tabs{grid-template-columns:repeat(3,1fr)}.filters{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.report-tabs{grid-template-columns:repeat(2,1fr)}.filters{grid-template-columns:1fr}.report-heading{display:block}.period{text-align:left;margin-top:12px}.formula-grid{grid-template-columns:1fr 1fr}}
`]})
export class ReportsComponent implements OnInit{
 private api=inject(ApiService);data:any={};employees:any[]=[];projects:any[]=[];loading=false;error='';showFormula=false;active:TabKey='kpi';generatedAt=new Date();formula:any;rows:any[]=[];columns:Column[]=[];totals=true;
 from=new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10);to=new Date().toISOString().slice(0,10);employeeId:number|null=null;projectId:number|null=null;
 tabs=[
  {key:'kpi' as TabKey,icon:'K',label:'Employee KPI',description:'Score and accountability',title:'Employee performance scorecard',help:'Ranked evaluation using response, sales, collection, outcome and follow-up performance.'},
  {key:'leads' as TabKey,icon:'L',label:'Lead Summary',description:'Pipeline essentials',title:'Lead summary',help:'The minimum operational view of lead volume, ownership and outcomes.'},
  {key:'sales' as TabKey,icon:'S',label:'Sales Summary',description:'Units and value',title:'Sales summary',help:'Booked units and agreed sales value by employee and project.'},
  {key:'collections' as TabKey,icon:'৳',label:'Collections',description:'Target performance',title:'Collection summary',help:'Monthly collection results against assigned employee targets.'},
  {key:'returned' as TabKey,icon:'!',label:'Returned Leads',description:'Response risk',title:'Returned lead accountability',help:'Leads returned after the employee missed the configured response deadline.'},
  {key:'projects' as TabKey,icon:'P',label:'Projects',description:'Project outcomes',title:'Project performance',help:'Lead outcomes, sold units and booked value by project.'}
 ];
 configs:Record<TabKey,Column[]>={
  kpi:[{key:'employee',label:'Employee'},{key:'team',label:'Team'},{key:'score',label:'KPI Score'},{key:'rating',label:'Rating'},{key:'won',label:'Won',type:'number'},{key:'lost',label:'Lost',type:'number'},{key:'returned',label:'Returned',type:'number',accent:true},{key:'returnedRate',label:'Return Rate',type:'percent',accent:true},{key:'salesUnits',label:'Sales Units',type:'number'},{key:'salesAchievement',label:'Sales Target',type:'percent'},{key:'collections',label:'Collections',type:'money'},{key:'collectionAchievement',label:'Collection Target',type:'percent'},{key:'winRate',label:'Win Rate',type:'percent'},{key:'followupCoverage',label:'Follow-up',type:'percent'}],
  leads:[{key:'totalLeads',label:'Total Leads',type:'number'},{key:'newLeads',label:'New',type:'number'},{key:'assigned',label:'Assigned',type:'number'},{key:'unassigned',label:'Unassigned',type:'number'},{key:'active',label:'Active',type:'number'},{key:'won',label:'Won',type:'number'},{key:'lost',label:'Lost',type:'number'},{key:'returned',label:'Returned',type:'number',accent:true},{key:'awaitingFollowUp',label:'Awaiting Follow-up',type:'number'}],
  sales:[{key:'employee',label:'Employee'},{key:'project',label:'Project'},{key:'salesUnits',label:'Sales Units',type:'number'},{key:'agreedSalesValue',label:'Agreed Sales Value',type:'money'},{key:'won',label:'Won',type:'number'},{key:'lost',label:'Lost',type:'number'}],
  collections:[{key:'employee',label:'Employee'},{key:'month',label:'Month',type:'date'},{key:'target',label:'Target',type:'money'},{key:'collected',label:'Collected',type:'money'},{key:'variance',label:'Variance',type:'money'},{key:'achievement',label:'Achievement',type:'percent'}],
  returned:[{key:'lead',label:'Lead / Customer'},{key:'employee',label:'Responsible Employee',accent:true},{key:'project',label:'Project'},{key:'assignedAt',label:'Assigned',type:'datetime'},{key:'returnedAt',label:'Returned',type:'datetime',accent:true},{key:'notificationCount',label:'Reminders',type:'number'},{key:'status',label:'Current Status'},{key:'currentEmployee',label:'Current Assignment'}],
  projects:[{key:'project',label:'Project'},{key:'leadsReceived',label:'Leads',type:'number'},{key:'won',label:'Won',type:'number'},{key:'lost',label:'Lost',type:'number'},{key:'salesUnits',label:'Sales Units',type:'number'},{key:'collectionAmount',label:'Agreed Sales Value',type:'money'}]
 };
 ngOnInit(){this.api.salesExecutives().subscribe({next:x=>this.employees=x});this.api.projects().subscribe({next:x=>this.projects=x});this.load()}
 get activeTab(){return this.tabs.find(x=>x.key===this.active)!}
 load(){this.loading=true;this.error='';this.api.reportWorkspace(this.from,this.to,this.employeeId,this.projectId).subscribe({next:r=>{this.data=r;this.formula=r.formula;this.generatedAt=new Date(r.generatedAt);this.applyTab();this.loading=false},error:e=>{this.error=e.error?.message||'Could not load reports.';this.loading=false}})}
 select(key:TabKey){this.active=key;this.applyTab()}
 applyTab(){const keys:Record<TabKey,string>={kpi:'kpis',leads:'leadSummary',sales:'salesSummary',collections:'collectionSummary',returned:'returnedLeads',projects:'projectSummary'};this.rows=this.data[keys[this.active]]||[];this.columns=this.configs[this.active];this.totals=this.active!=='returned'&&this.active!=='kpi'}
 display(value:any,type?:Column['type']){if(value===null||value===undefined||value==='')return '—';if(type==='money')return new Intl.NumberFormat('en-BD',{style:'currency',currency:'BDT',maximumFractionDigits:0}).format(Number(value));if(type==='percent')return `${Number(value).toFixed(1)}%`;if(type==='number')return new Intl.NumberFormat('en-BD').format(Number(value));if(type==='date'||type==='datetime'){const d=new Date(value);return isNaN(d.valueOf())?String(value):d.toLocaleString('en-BD',type==='date'?{month:'short',year:'numeric'}:{dateStyle:'medium',timeStyle:'short'})}return String(value)}
 ratingClass(value:string){return value==='Excellent'?'excellent':value==='Good'?'good':value==='Needs improvement'?'improve':'critical'}
 totalValue(column:Column){if(!column.type||column.type==='date'||column.type==='datetime')return '—';const sum=this.rows.reduce((n,r)=>n+(Number(r[column.key])||0),0);return this.display(sum,column.type)}
 exportCsv(){const q=(v:any)=>`"${String(v??'').replace(/"/g,'""')}"`;const csv='\ufeff'+this.columns.map(x=>q(x.label)).join(',')+'\r\n'+this.rows.map(row=>this.columns.map(c=>q(this.display(row[c.key],c.type))).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`${this.active}-report-${this.from}-${this.to}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
}
